ALTER TABLE "public"."EventReminder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."CalendarSyncCredential" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ShareInvite" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Event" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ReminderDeliverySetting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ReminderQueueJob" ENABLE ROW LEVEL SECURITY;
